# database init, supports postgres too
database=postgres
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
spring.datasource.username=${POSTGRES_USER:calvino}
spring.datasource.password=${POSTGRES_PASS:210921}
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
